Arysoft.WebsiteMVC.Basico/Areas/Admin/Controllers/PaginasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Web;
using System.Web.Mvc;
using Arysoft.WebsiteMVC.Basico.Models;
using Arysoft.WebsiteMVC.Basico.Areas.Admin.Models;
using PagedList;

namespace Arysoft.WebsiteMVC.Basico.Areas.Admin.Controllers
{
    public class PaginasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Paginas
        public async Task<ActionResult> Index(string buscar, string filtro, string orden, string status, int? pagina)
        {
            PaginaStatus myStatus = (PaginaStatus)(string.IsNullOrEmpty(status) ? PaginaStatus.Ninguno : Enum.Parse(typeof(PaginaStatus), status));

            ViewBag.MenuActive = "paginas";

            ViewBag.Orden = orden;
            ViewBag.OrdenTitulo = string.IsNullOrEmpty(orden) ? "titulo_desc" : "";
            ViewBag.OrdenFecha = orden == "fecha" ? "fecha_desc" : "fecha";
            ViewBag.OrdenVisitas = orden == "visitas" ? "visitas_desc" : "visitas";
            ViewBag.OrdenMeGusta = orden == "megusta" ? "megusta_desc" : "megusta";
            if (buscar != null)
            {
                pagina = 1;
                buscar = buscar.Trim();
            }
            else { buscar = filtro ?? string.Empty; }
            ViewBag.Filtro = buscar;
            var paginas = db.Paginas
                .Include(p => p.PaginaPadre)
                .Include(p => p.Archivos)
                .Include(p => p.Notas)
                .Where(p => p.Status != PaginaStatus.Ninguno);
            if (!string.IsNullOrEmpty(buscar) || myStatus != PaginaStatus.Ninguno)
            {
                bool hayPalabras = !string.IsNullOrEmpty(buscar);

                paginas = paginas.Where(p => 
                    (
                        (!hayPalabras)
                        || p.Titulo.Contains(buscar)
                        || p.Resumen.Contains(buscar)
                        || p.HTMLContent.Contains(buscar)
                    )
                    && (myStatus == PaginaStatus.Ninguno ? true : p.Status == myStatus)
                );
            }
            switch (orden)
            {
                case "titulo_desc":
                    paginas = paginas.OrderByDescending(p => p.Titulo);
                    break;
                case "fecha":
                    paginas = paginas.OrderBy(p => p.FechaActualizacion);
                    break;
                case "fecha_desc":
                    paginas = paginas.OrderByDescending(p => p.FechaActualizacion);
                    break;
                case "visitas":
                    paginas = paginas.OrderBy(p => p.ContadorVisitas);
                    break;
                case "visitas_desc":
                    paginas = paginas.OrderBy(p => p.ContadorVisitas);
                    break;
                case "megusta":
                    paginas = paginas.OrderBy(p => p.MeGusta);
                    break;
                case "megusta_desc":
                    paginas = paginas.OrderByDescending(p => p.MeGusta);
                    break;
                default:
                    paginas = paginas.OrderBy(p => p.Titulo);
                    break;
            }
            List<PaginaIndexListViewModel> paginasViewModel = new List<PaginaIndexListViewModel>();
            foreach (Pagina miPagina in await paginas.ToListAsync())
            {
                paginasViewModel.Add(new PaginaIndexListViewModel(miPagina));
            }
            ViewBag.Count = paginasViewModel.Count();
            int numeroPagina = pagina ?? 1;
            int elementosPagina = Comun.ELEMENTOS_PAGINA;

            return View(paginasViewModel.ToPagedList(numeroPagina, elementosPagina));
        } // Index

        // GET: Admin/Paginas/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                TempData["MessageBox"] = "No se recibió el identificador";
                if (Request.IsAjaxRequest()) return Content("BadRequest");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pagina pagina = await db.Paginas
                .Include(p => p.Archivos)
                .Include(p => p.Notas)
                .Include(p => p.PaginaPadre)
                .Include(p => p.PaginasHijo)
                .FirstOrDefaultAsync(p => p.PaginaID == id);
            if (pagina == null)
            {
                TempData["MessageBox"] = "No se encontró el registro del identificador";
                if (Request.IsAjaxRequest()) return Content("HttpNotFound");
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
            {
                TempData["isReadonly"] = true;
                TempData["isPage"] = true;
                PaginaDetailsViewModel p = new PaginaDetailsViewModel(pagina, "details", true);
                return PartialView("_details", p);
            }
            return View(pagina);
        } // Details

        // GET: Admin/Paginas/Create
        public async Task<ActionResult> Create()
        {
            await EliminarRegistrosTemporalesAsync(User.Identity.Name);

            Pagina pagina = new Pagina
            {
                PaginaID = Guid.NewGuid(),
                IndiceMenu = 0,
                Target = PaginaTarget.Ninguno,
                ContadorVisitas = 0,
                TieneGaleria = BoolTipo.Ninguno,
                FechaContador = DateTime.Now,
                Idioma = IdiomaTipo.Ninguno,
                EsPrincipal = BoolTipo.Ninguno,
                MeGusta = 0,
                Status = PaginaStatus.Ninguno,
                FechaCreacion = DateTime.Now,
                FechaActualizacion = DateTime.Now,
                UsuarioActualizacion = User.Identity.Name
            };

            db.Paginas.Add(pagina);

            try
            {
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", new { id = pagina.PaginaID });
            }
            catch (Exception e)
            {
                TempData["MessageBox"] = "Ha ocurrido una excepción: " + e.Message;
                return RedirectToAction("Index");
            }
        } // Create

        //// POST: Admin/Paginas/Create
        //// Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        //// más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "PaginaID,PaginaPadreID,Titulo,EtiquetaMenu,Resumen,HtmlContent,Visible,TargetUrl,Target,TieneGaleria,ContadorVisitas,FechaContador,Idioma,EsPrincipal,HTMLHeadScript,HTMLFooterScript,MeGusta,Status,FechaCreacion,FechaActualizacion,UsuarioActualizacion")] Pagina pagina)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        pagina.PaginaID = Guid.NewGuid();
        //        db.Paginas.Add(pagina);
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.PaginaPadreID = new SelectList(db.Paginas, "PaginaID", "Titulo", pagina.PaginaPadreID);
        //    return View(pagina);
        //}

        // GET: Admin/Paginas/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                TempData["MessageBox"] = "No se recibió el identificador.";
                return RedirectToAction("Index");
            }
            Pagina pagina = await db.Paginas
                .Include(p => p.Archivos)
                .Include(p => p.Notas)
                .Include(p => p.PaginasHijo)
                .FirstOrDefaultAsync(p => p.PaginaID == id);
            if (pagina == null)
            {
                TempData["MessageBox"] = "No se encontró el registro.";
                return RedirectToAction("Index");
                //return HttpNotFound();
            }
            if (pagina.Status == PaginaStatus.Eliminada)
            {
                TempData["MessageBox"] = "La página ha sido eliminada.";
                return RedirectToAction("Index");
            }
            TempData["isReadonly"] = false;
            TempData["isPage"] = true;
            
            ViewBag.PaginaPadreID = await ListaPaginasPadreAsync(pagina.PaginaPadreID ?? Guid.Empty, pagina.PaginaID);

            return View(new PaginaEditViewModel(pagina));
        } // Edit

        // POST: Admin/Paginas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PaginaID,PaginaPadreID,Titulo,EtiquetaMenu,__resumen,__content,TargetUrl,Target,TieneGaleria,ContadorVisitas,FechaContador,Idioma,EsPrincipal,__headScript,__footerScript,MeGusta,Status,FechaCreacion,OrdenPaginasHijo")] PaginaEditViewModel paginaVM)
        {
            Pagina pagina = paginaVM.ObtenerPagina();
            bool esNuevo = pagina.Status == PaginaStatus.Ninguno;

            if (esNuevo)
            {
                pagina.Status = PaginaStatus.Nueva;
            }

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(paginaVM.OrdenPaginasHijo)) // Ordenar el indice de las páginas hijo
                {
                    string[] ids = paginaVM.OrdenPaginasHijo.Split(',');
                    int indice = 0;

Arysoft.WebsiteMVC.Basico/Views/Shared/_Layout.cshtml
@{    
    string messageBox = string.Empty;
    string showMessageBox = string.Empty;

    if (TempData["MessageBox"] != null)
    {
        messageBox = TempData["MessageBox"].ToString().Replace(Environment.NewLine, "<br />");
        showMessageBox = "$('#messageBoxModal').modal('show');";
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Arysoft</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/Site.css?v=1" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("stylesheets", required: false)

</head>
<body>

    <div id="messageBoxModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body">
                    @messageBox
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Arysoft", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, null)</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Páginas", "Index", "Pagina", new { area = "Admin" }, null)</li>
                            <li>@Html.ActionLink("Noticias", "Index", "Noticia", new { area = "Admin" }, null)</li>
                            <li>@Html.ActionLink("Usuarios", "Index", "Usuario", new { area = "Admin" }, null)</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @Html.ActionLink("Basic Website", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                @Html.ActionLink("Páginas", "Index", "Paginas", new { area = "Admin" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Noticias", "Index", "Noticias", new { area = "Admin" }, new { @class = "dropdown-item" })
                                @Html.ActionLink("Usuarios", "Index", "Usuarios", new { area = "Admin" }, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Movie App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        @Html.Raw(showMessageBox)
    </script>
</body>
</html>